@extends('layouts.app')
@section('content')
<div class="d-flex justify-content-between"><h1>Quote #{{ $quote->id }}</h1><div><a class="btn btn-outline-secondary" href="{{ route('admin.quotes.edit',$quote) }}">Edit</a><form method="POST" action="{{ route('admin.quotes.send',$quote) }}" class="d-inline">@csrf<button class="btn btn-warning">Send to Customer</button></form></div></div>
<div class="card mb-4"><div class="card-body"><p><strong>Customer:</strong> {{ $quote->partRequest->customer->name }} / {{ $quote->partRequest->customer->email }}</p><p><strong>Public quote link:</strong> <a href="{{ route('quotes.public.show',$quote) }}">{{ route('quotes.public.show',$quote) }}</a></p><p><strong>Status:</strong> {{ $quote->status->value }}</p><h3>Total: {{ $quote->currency }} {{ number_format($quote->total(),2) }}</h3></div></div>
<div class="card mb-4"><div class="card-body"><h3>Add Item</h3><form method="POST" action="{{ route('admin.quotes.items.store',$quote) }}" class="row g-2">@csrf
<div class="col-md-4"><input name="description" class="form-control" placeholder="Part description" required></div><div class="col-md-3"><input name="supplier_name" class="form-control" placeholder="Supplier"></div><div class="col-md-2"><input name="quantity" type="number" class="form-control" value="1" required></div><div class="col-md-2"><input name="unit_price" type="number" step="0.01" class="form-control" placeholder="Unit price" required></div><div class="col-md-1"><button class="btn btn-dark">Add</button></div>
</form></div></div>
<table class="table card card-body"><tr><th>Description</th><th>Supplier</th><th>Qty</th><th>Total</th><th></th></tr>@foreach($quote->items as $item)<tr><td>{{ $item->description }}</td><td>{{ $item->supplier_name }}</td><td>{{ $item->quantity }}</td><td>{{ $quote->currency }} {{ number_format($item->total_price,2) }}</td><td><form method="POST" action="{{ route('admin.quotes.items.destroy',$item) }}">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">Remove</button></form></td></tr>@endforeach</table>
@endsection
